export const ACTION_SAGA_BACK_HOME = '@@HEADER/SAGA/BACK_HOME';
export const ACTION_SAGA_CALL_SERVICES = '@@HEADER/SAGA/CALL_SERVICES';
export const ACTION_SAGA_HANGUP_SERVICES = '@@HEADER/SAGA/HANGUP_SERVICES';
export const ACTION_SAGA_REGIST_EVENT = '@@HEADER/SAGA/REGIST_EVENT';
export const ACTION_SAGA_UNREGIST_EVENT = '@@HEADER/SAGA/UNREGIST_EVENT';
